#!/bin/bash

#
# bash_profile (MXDF::BASH)
#

# Define MXDF as the active Dot Files
export MXDF_ACTIVE=1

# Path to the BASH section
export MXDF_BASH=$HOME/.bash

# Path to the BIN section (binaries directory)
export MXDF_BIN=$HOME/.bin

# Name of the 'local' component (i.e. custom directory) inside the BASH
# section. Only the name, no leading or trailing '/'.
export BASH_LOCAL_COMPONENT='local'

# --------------------------------------------------------------------------------------------------

# Path to the 'local' component inside the BASH section
export MXDF_BASH_LOCAL=$MXDF_BASH/$BASH_LOCAL_COMPONENT

# Load the '!bash_profile.<local-component>.bash' file for any modifications
# needed. Note this file will not be loaded thru '_load_component()' due to the
# '!' in the filename.
[ -s $MXDF_BASH_LOCAL/!bash_profile.$BASH_LOCAL_COMPONENT.bash ] && . $MXDF_BASH_LOCAL/!bash_profile.$BASH_LOCAL_COMPONENT.bash

# Include the MXDF_BIN directory in the PATH
[ -d $MXDF_BIN ] && PATH=$MXDF_BIN:$PATH

# Export the PATH variable
export PATH

# Several Distros has changed the default system shell (/bin/sh) to different
# command interpreters (i.e. DASH). So load the '~/.bashrc' file only when BASH
# is the current subshell and if there is a '~/.bashrc'.
#
# Another solution could be to modify the default shell at the system level
# (sudo dpkg-reconfigure dash), but this will affect overall performance.
[ -n "$BASH" ] && [ -s $HOME/.bashrc ] && source $HOME/.bashrc
